export const LP_IMG_EMAIL = require ('../../Assets/Images/ic_email.png')
export const LP_IMG_PASSWORD = require ('../../Assets/Images/ic_password.png')
export const RP_IMG_BACK = require ('../../Assets/Images/ic_back.png')
export const RP_IMG_USERNAME = require ('../../Assets/Images/ic_username.png')
export const RP_IMG_CHECK = require ('../../Assets/Images/ic_check.png')
export const RP_IMG_UNCHECK = require ('../../Assets/Images/ic_uncheck.png')
export const RP_IMG_PHONE = require ('../../Assets/Images/ic_phone.png')
export const RP_IMG_UNCHECKTERMS = require ('../../Assets/Images/ic_uncheck_terms.png')
export const RP_IMG_CHECKTERMS = require ('../../Assets/Images/ic_check_terms.png')
export const HOME_IMG_TABLE = require ('../../Assets/Images/ic_home_table.png')
export const HOME_IMG_SOFA = require ('../../Assets/Images/ic_home_sofa.png')
export const HOME_IMG_CUPBOARD = require ('../../Assets/Images/ic_home_cupboard.png')
export const HOME_IMG_CHAIR = require ('../../Assets/Images/ic_home_chair.png')

export const HOME_SLIDER_1 = require ('../../Assets/Images/ic_slider_1.jpg')
export const HOME_SLIDER_2 = require ('../../Assets/Images/ic_slider_2.jpg')
export const HOME_SLIDER_3 = require ('../../Assets/Images/ic_slider_3.jpg')
export const HOME_SLIDER_4 = require ('../../Assets/Images/ic_slider_4.jpg')

export const PROD_CHECK_STAR = require('../../Assets/Images/ic_star_check.png')
export const PROD_UNCHECK_STAR = require('../../Assets/Images/ic_star_unchek.png')
export const PROD_SHARE = require('../../Assets/Images/ic_share.png')
