export const PRODUCT_DETAIL = 'PRODUCT_DETAIL'
export const LOADER = 'PROD_DETAIL_LOADER'
export const PRODUCT_DETAIL_FAIL= 'PRODUCT_DETAIL_FAIL'
export const BUY = 'BUY'
export const BUY_FAIL = 'BUY_FAIL'
